from . import booking_request_vts
from . import service_type_vts
from . import cleaning_shift_vts
from . import cleaning_team_vts
from . import project_task
from . import hr_employee
from . import booking_dashboard_vts
from . import account_move
from . import cleaning_holiday_vts
from . import empl_availability_vts
from . import hr_timesheet_stop_timer_confirmation_wizard